name: Validate code and build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt

      - run: cargo fmt --all -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings

      - run: cargo install cargo-audit
      - run: cargo audit

  build-and-test:
    needs: validate-code
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run cargo build
        run: cargo build --target ${{ matrix.target }} --all-features

      - name: Run cargo test
        run: cargo test --target ${{ matrix.target }} --all-features -- --test-threads=1
